# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from spell.driver.v1 import driver_pb2 as spell_dot_driver_dot_v1_dot_driver__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in spell/driver/v1/driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DriverInfrastructureServiceStub:
    """The legacy infrastructure lifecycle service retains exactly its original nine
    unary RPCs. The separate read-only observation service below is additive.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.unary_unary(
                '/spell.driver.v1.DriverInfrastructureService/Handshake',
                request_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/spell.driver.v1.DriverInfrastructureService/Health',
                request_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.HealthRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.OpenContext = channel.unary_unary(
                '/spell.driver.v1.DriverInfrastructureService/OpenContext',
                request_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.OpenContextRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.FromString,
                _registered_method=True)
        self.CloseContext = channel.unary_unary(
                '/spell.driver.v1.DriverInfrastructureService/CloseContext',
                request_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.CloseContextRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.FromString,
                _registered_method=True)
        self.AttachExecution = channel.unary_unary(
                '/spell.driver.v1.DriverInfrastructureService/AttachExecution',
                request_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.AttachExecutionRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.FromString,
                _registered_method=True)
        self.DetachExecution = channel.unary_unary(
                '/spell.driver.v1.DriverInfrastructureService/DetachExecution',
                request_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.DetachExecutionRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.FromString,
                _registered_method=True)
        self.CancelLifecycleOperation = channel.unary_unary(
                '/spell.driver.v1.DriverInfrastructureService/CancelLifecycleOperation',
                request_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.CancelLifecycleOperationRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.FromString,
                _registered_method=True)
        self.DrainHost = channel.unary_unary(
                '/spell.driver.v1.DriverInfrastructureService/DrainHost',
                request_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.DrainHostRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.FromString,
                _registered_method=True)
        self.GetOperation = channel.unary_unary(
                '/spell.driver.v1.DriverInfrastructureService/GetOperation',
                request_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.GetOperationRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.GetOperationResponse.FromString,
                _registered_method=True)


class DriverInfrastructureServiceServicer:
    """The legacy infrastructure lifecycle service retains exactly its original nine
    unary RPCs. The separate read-only observation service below is additive.
    """

    def Handshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetachExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelLifecycleOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrainHost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverInfrastructureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.HandshakeRequest.FromString,
                    response_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.HandshakeResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.HealthRequest.FromString,
                    response_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.HealthResponse.SerializeToString,
            ),
            'OpenContext': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenContext,
                    request_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.OpenContextRequest.FromString,
                    response_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.SerializeToString,
            ),
            'CloseContext': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseContext,
                    request_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.CloseContextRequest.FromString,
                    response_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.SerializeToString,
            ),
            'AttachExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.AttachExecution,
                    request_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.AttachExecutionRequest.FromString,
                    response_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.SerializeToString,
            ),
            'DetachExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.DetachExecution,
                    request_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.DetachExecutionRequest.FromString,
                    response_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.SerializeToString,
            ),
            'CancelLifecycleOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelLifecycleOperation,
                    request_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.CancelLifecycleOperationRequest.FromString,
                    response_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.SerializeToString,
            ),
            'DrainHost': grpc.unary_unary_rpc_method_handler(
                    servicer.DrainHost,
                    request_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.DrainHostRequest.FromString,
                    response_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.SerializeToString,
            ),
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.GetOperationRequest.FromString,
                    response_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.GetOperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spell.driver.v1.DriverInfrastructureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spell.driver.v1.DriverInfrastructureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriverInfrastructureService:
    """The legacy infrastructure lifecycle service retains exactly its original nine
    unary RPCs. The separate read-only observation service below is additive.
    """

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.v1.DriverInfrastructureService/Handshake',
            spell_dot_driver_dot_v1_dot_driver__pb2.HandshakeRequest.SerializeToString,
            spell_dot_driver_dot_v1_dot_driver__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.v1.DriverInfrastructureService/Health',
            spell_dot_driver_dot_v1_dot_driver__pb2.HealthRequest.SerializeToString,
            spell_dot_driver_dot_v1_dot_driver__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.v1.DriverInfrastructureService/OpenContext',
            spell_dot_driver_dot_v1_dot_driver__pb2.OpenContextRequest.SerializeToString,
            spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.v1.DriverInfrastructureService/CloseContext',
            spell_dot_driver_dot_v1_dot_driver__pb2.CloseContextRequest.SerializeToString,
            spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AttachExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.v1.DriverInfrastructureService/AttachExecution',
            spell_dot_driver_dot_v1_dot_driver__pb2.AttachExecutionRequest.SerializeToString,
            spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetachExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.v1.DriverInfrastructureService/DetachExecution',
            spell_dot_driver_dot_v1_dot_driver__pb2.DetachExecutionRequest.SerializeToString,
            spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelLifecycleOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.v1.DriverInfrastructureService/CancelLifecycleOperation',
            spell_dot_driver_dot_v1_dot_driver__pb2.CancelLifecycleOperationRequest.SerializeToString,
            spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrainHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.v1.DriverInfrastructureService/DrainHost',
            spell_dot_driver_dot_v1_dot_driver__pb2.DrainHostRequest.SerializeToString,
            spell_dot_driver_dot_v1_dot_driver__pb2.LifecycleOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.v1.DriverInfrastructureService/GetOperation',
            spell_dot_driver_dot_v1_dot_driver__pb2.GetOperationRequest.SerializeToString,
            spell_dot_driver_dot_v1_dot_driver__pb2.GetOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DriverObservationServiceStub:
    """The observation service is additive. It does not create lifecycle operations,
    consume lifecycle capacity, or alter the legacy infrastructure capability set.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTime = channel.unary_unary(
                '/spell.driver.v1.DriverObservationService/GetTime',
                request_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.GetTimeRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.GetTimeResponse.FromString,
                _registered_method=True)
        self.GetTM = channel.unary_unary(
                '/spell.driver.v1.DriverObservationService/GetTM',
                request_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.GetTMRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.GetTMResponse.FromString,
                _registered_method=True)


class DriverObservationServiceServicer:
    """The observation service is additive. It does not create lifecycle operations,
    consume lifecycle capacity, or alter the legacy infrastructure capability set.
    """

    def GetTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverObservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTime,
                    request_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.GetTimeRequest.FromString,
                    response_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.GetTimeResponse.SerializeToString,
            ),
            'GetTM': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTM,
                    request_deserializer=spell_dot_driver_dot_v1_dot_driver__pb2.GetTMRequest.FromString,
                    response_serializer=spell_dot_driver_dot_v1_dot_driver__pb2.GetTMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spell.driver.v1.DriverObservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spell.driver.v1.DriverObservationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriverObservationService:
    """The observation service is additive. It does not create lifecycle operations,
    consume lifecycle capacity, or alter the legacy infrastructure capability set.
    """

    @staticmethod
    def GetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.v1.DriverObservationService/GetTime',
            spell_dot_driver_dot_v1_dot_driver__pb2.GetTimeRequest.SerializeToString,
            spell_dot_driver_dot_v1_dot_driver__pb2.GetTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.v1.DriverObservationService/GetTM',
            spell_dot_driver_dot_v1_dot_driver__pb2.GetTMRequest.SerializeToString,
            spell_dot_driver_dot_v1_dot_driver__pb2.GetTMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
