"""Independent direct-source scalar and control-flow oracles for v0.17."""
from .language_conformance_v16 import _case

_MAX_INT = (1 << 4096) - 1
_RANGE = ("SYNTAX-FOR-IN", "METHOD-CONVERSION-RANGE")
_BRANCH = ("SYNTAX-IF-ELIF-ELSE",)
_POWER = ("OPERATOR-PYTHON-POWER",)

CASES = (
    _case("v17-core-arithmetic-precedence", 'value = -3 + 4 * 5\npositive = +7\nratio = 9 / 2\nDisplay("precedence")\n',
          variables={"value": 17, "positive": 7, "ratio": 4.5}, logs=[("precedence", "info")],
          artifacts=("OPERATOR-PYTHON-ADD", "OPERATOR-PYTHON-SUBTRACT", "OPERATOR-PYTHON-MULTIPLY", "OPERATOR-PYTHON-DIVIDE")),
    _case("v17-core-signed-modulus", 'left = -7 % 3\nright = 7 % -3\nDisplay("signed modulus")\n',
          variables={"left": 2, "right": -2}, logs=[("signed modulus", "info")], artifacts=("OPERATOR-PYTHON-MODULUS",)),
    _case("v17-core-mixed-numeric", 'value: float = 2\nvalue = value + 0.5\nvalid = value == 2.5\nDisplay("numeric")\n',
          variables={"value": 2.5, "valid": True}, logs=[("numeric", "info")], artifacts=("TYPE-FLOAT", "TYPE-INTEGER")),
    _case("v17-core-chained-short-circuit", 'valid = 3 < 2 < (1 / 0)\nDisplay("comparison stopped")\n',
          variables={"valid": False}, logs=[("comparison stopped", "info")], artifacts=("OPERATOR-PYTHON-LESS",)),
    _case("v17-core-chained-all-true", 'valid = -2 < -1 <= -1 < 0\nDisplay("comparison")\n',
          variables={"valid": True}, logs=[("comparison", "info")], artifacts=("OPERATOR-PYTHON-LESS", "OPERATOR-PYTHON-LESS-EQUAL")),
    _case("v17-core-boolean-short-circuit", 'left = False and (1 / 0 > 0)\nright = True or (1 / 0 > 0)\nvalue = not left and right\nDisplay("short circuit")\n',
          variables={"left": False, "right": True, "value": True}, logs=[("short circuit", "info")],
          artifacts=("OPERATOR-PYTHON-AND", "OPERATOR-PYTHON-OR", "OPERATOR-PYTHON-NOT")),
    _case("v17-core-boolean-evaluated-error", 'value = True and (1 / 0 > 0)\nDisplay("unreachable")\n', terminal="failed"),
    _case("v17-core-if-first-captured", 'choice = 1\nresult = "none"\nif choice == 1:\n    choice = 2\n    result = "first"\nelif choice == 2:\n    result = "second"\nelse:\n    result = "last"\nDisplay(result)\n',
          variables={"choice": 2, "result": "first"}, logs=[("first", "info")], artifacts=_BRANCH),
    _case("v17-core-if-elif", 'choice = 2\nresult = "none"\nif choice == 1:\n    result = "first"\nelif choice == 2:\n    result = "second"\nelse:\n    result = "last"\nDisplay(result)\n',
          variables={"result": "second"}, logs=[("second", "info")], artifacts=_BRANCH),
    _case("v17-core-if-else", 'choice = 3\nresult = "none"\nif choice == 1:\n    result = "first"\nelif choice == 2:\n    result = "second"\nelse:\n    result = "last"\nDisplay(result)\n',
          variables={"result": "last"}, logs=[("last", "info")], artifacts=_BRANCH),
    _case("v17-core-if-no-else", 'result = "retained"\nif False:\n    result = "wrong"\nDisplay(result)\n',
          variables={"result": "retained"}, logs=[("retained", "info")], artifacts=_BRANCH),
    _case("v17-core-nested-dead-condition", 'result = "retained"\nif False:\n    if 1 / 0 > 0:\n        result = "wrong"\nDisplay(result)\n',
          variables={"result": "retained"}, logs=[("retained", "info")], artifacts=_BRANCH),
    _case("v17-core-empty-range", 'total = 7\nfor item in range(0):\n    total += item\n    Display("unreachable")\nDisplay("empty")\n',
          variables={"total": 7}, logs=[("empty", "info")], artifacts=_RANGE),
    _case("v17-core-equal-range", 'total = 7\nfor item in range(3, 3):\n    total += item\nDisplay("equal")\n',
          variables={"total": 7}, logs=[("equal", "info")], artifacts=_RANGE),
    _case("v17-core-wrong-direction-ranges", 'total = 7\nfor item in range(3, 1, 1):\n    total += item\nfor item in range(1, 3, -1):\n    total += item\nDisplay("directions")\n',
          variables={"total": 7}, logs=[("directions", "info")], artifacts=_RANGE),
    _case("v17-core-empty-retains-prior-index", 'item = 9\nfor item in range(0):\n    item += 10\nDisplay("retained")\n',
          variables={"item": 9}, logs=[("retained", "info")], artifacts=_RANGE),
    _case("v17-core-singleton-range", 'total = 0\nfor item in range(-3, -2):\n    total += item\nDisplay("singleton")\n',
          variables={"total": -3}, logs=[("singleton", "info")], artifacts=_RANGE),
    _case("v17-core-negative-step-range", 'total = 0\nfor item in range(5, -2, -2):\n    total += item\nDisplay("descending")\n',
          variables={"total": 8}, logs=[("descending", "info")], artifacts=_RANGE),
    _case("v17-core-maximum-range", 'total = 0\nfor item in range(1000):\n    total += item\nDisplay("bounded")\n',
          variables={"total": 499500}, logs=[("bounded", "info")], artifacts=_RANGE),
    _case("v17-core-nested-empty-range", 'total = 0\nfor outer in range(3):\n    for inner in range(0):\n        total += 100\n    total += 1\nDisplay("nested")\n',
          variables={"total": 3}, logs=[("nested", "info")], artifacts=_RANGE),
    _case("v17-core-bitwise-signed", 'both = -6 & 3\neither = -6 | 3\nprecedence = 2 | 6 & 3\nDisplay("bits")\n',
          variables={"both": 2, "either": -5, "precedence": 2}, logs=[("bits", "info")],
          artifacts=("OPERATOR-PYTHON-BITWISE-AND", "OPERATOR-PYTHON-BITWISE-OR")),
    _case("v17-core-bitwise-bound", f'limit = {hex(_MAX_INT)}\nresult = limit & -1\nDisplay("bit bound")\n',
          variables={"result": _MAX_INT}, logs=[("bit bound", "info")], artifacts=("OPERATOR-PYTHON-BITWISE-AND",)),
    _case("v17-core-power-sign-precedence", 'negative = -2 ** 2\npositive = (-2) ** 2\nodd = (-2) ** 3\nright_associative = 2 ** 3 ** 2\nDisplay("powers")\n',
          variables={"negative": -4, "positive": 4, "odd": -8, "right_associative": 512}, logs=[("powers", "info")], artifacts=_POWER),
    _case("v17-core-power-zero-one", 'zero = 0 ** 2\nidentity = 0 ** 0\nunit = (-1) ** 4096\nexponent = 3\nvariable = 2 ** exponent\nDisplay("identities")\n',
          variables={"zero": 0, "identity": 1, "unit": 1, "variable": 8}, logs=[("identities", "info")], artifacts=_POWER),
    _case("v17-core-power-result-bound", 'result = 2 ** 4095\nDisplay("power bound")\n',
          variables={"result": 1 << 4095}, logs=[("power bound", "info")], artifacts=_POWER),
    _case("v17-core-power-result-overflow", 'result = 2 ** 4096\nDisplay("unreachable")\n', terminal="failed", artifacts=_POWER),
    _case("v17-core-power-variable-negative", 'exponent = -1\nresult = 2 ** exponent\nDisplay("unreachable")\n',
          variables={"exponent": -1}, terminal="failed"),
    _case("v17-core-power-variable-overflow", 'exponent = 4097\nresult = 2 ** exponent\nDisplay("unreachable")\n',
          variables={"exponent": 4097}, terminal="failed"),
    _case("v17-core-float-result-overflow", 'limit = 1e308\nresult = limit * 2.0\nDisplay("unreachable")\n',
          variables={"limit": 1e308}, terminal="failed"),
    _case("v17-core-reject-zero-step", 'for item in range(0, 1, 0):\n    Display("unreachable")\n', diagnostic="SPELL605"),
    _case("v17-core-reject-range-overflow", 'for item in range(1001):\n    Display("unreachable")\n', diagnostic="SPELL606"),
    _case("v17-core-reject-dynamic-range", 'limit = 2\nfor item in range(limit):\n    Display("unreachable")\n', diagnostic="SPELL604"),
    _case("v17-core-reject-dead-body-import", 'for item in range(0):\n    import os\nDisplay("unreachable")\n', diagnostic="SPELL103"),
    _case("v17-core-reject-dead-body-call", 'for item in range(0):\n    open("forbidden")\nDisplay("unreachable")\n', diagnostic="SPELL402"),
    _case("v17-core-reject-empty-index-read", 'for item in range(0):\n    Display("unreachable")\nvalue = item\nDisplay("unreachable")\n', diagnostic="SPELL308"),
    _case("v17-core-reject-integer-literal-overflow", f'value = {hex(1 << 4096)}\nDisplay("unreachable")\n', diagnostic="SPELL714"),
    _case("v17-core-reject-nonfinite-literal", 'value = 1e999\nDisplay("unreachable")\n', diagnostic="SPELL714"),
    _case("v17-core-reject-power-negative-literal", 'value = 2 ** -1\nDisplay("unreachable")\n', diagnostic="SPELL931"),
    _case("v17-core-reject-power-exponent-bound", 'value = 1 ** 4097\nDisplay("unreachable")\n', diagnostic="SPELL931"),
    _case("v17-core-reject-power-float", 'value = 2 ** 2.0\nDisplay("unreachable")\n', diagnostic="SPELL930"),
    _case("v17-core-reject-bitwise-bool", 'value = True & 1\nDisplay("unreachable")\n', diagnostic="SPELL930"),
    _case("v17-core-reject-numeric-condition", 'if 1:\n    Display("unreachable")\n', diagnostic="SPELL501"),
)
