# @procedure language_reference_244
# @display-name SPELL 2.4.4 reference examples
# @description Select and execute one of the 195 deterministic semantic adaptations
# @language-profile spell-lrm244-adapter/0.10
"""Run one bounded simulator adaptation from the SPELL 2.4.4 reference."""

selected_index: int = 0
example_number: int = 1
result: str = "not run"

Prompt(
    "Select a SPELL 2.4.4 reference example",
    type="LIST",
    choices=[
        "Example 001 - indentation",
        "Example 002 - splitting character strings",
        "Example 003 - splitting with comma",
        "Example 004 - splitting code with backslash",
        "Example 005 - single line comments in python",
        "Example 006 - multi-line comments in python",
        "Example 007 - variable types in Python",
        "Example 008 - lists and dictionaries",
        "Example 009 - arithmetic expressions",
        "Example 010 - boolean expressions",
        "Example 011 - string expressions",
        "Example 012 - substrings",
        "Example 013 - conditional statements",
        "Example 014 - for loop statements",
        "Example 015 - while loop statements",
        "Example 016 - user defined function example",
        "Example 017 - arguments by reference",
        "Example 018 - module (procedure) import",
        "Example 019 - SPELL function with keyword parameters",
        "Example 020 - changing defaults for a function in a procedure",
        "Example 021 - failure action configuration",
        "Example 022 - automatic failure processing",
        "Example 023 - reacting on function result",
        "Example 024 - special error handling",
        "Example 025 - silent execution",
        "Example 026 - using NOW in a loop",
        "Example 027 - using NOW in a loop (2)",
        "Example 028 - modifying the output time format",
        "Example 029 - time management",
        "Example 030 - obtain engineering TM values",
        "Example 031 - waiting for updates",
        "Example 032 - waiting for updates with timeout",
        "Example 033 - acquisition of raw value",
        "Example 034 - acquisition extended information",
        "Example 035 - verify a single TM value",
        "Example 036 - verify a single TM value in raw format",
        "Example 037 - verify using next update and timeout",
        "Example 038 - verify with tolerance",
        "Example 039 - using Verify in a test statement",
        "Example 040 - getting failure information",
        "Example 041 - getting failure information (output)",
        "Example 042 - do nothing on False",
        "Example 043 - do not prompt the user and take the SKIP action",
        "Example 044 - repeat verification if it fails, 2 times",
        "Example 045 - delay the verification",
        "Example 046 - ignoring string value case",
        "Example 047 - multiple verifications",
        "Example 048 - multiple verifications and configurations",
        "Example 049 - multiple verifications and configurations (2)",
        "Example 050 - verifications with multiple values",
        "Example 051 - comparing telemetry parameters",
        "Example 052 - comparing telemetry parameters (wrong code)",
        "Example 053 - comparing telemetry parameters with items",
        "Example 054 - comparing telemetry parameters with lists of items",
        "Example 055 - building a simple command",
        "Example 056 - building a simple command",
        "Example 057 - building a simple command",
        "Example 058 - command arguments",
        "Example 059 - building a command with arguments",
        "Example 060 - sending a simple command",
        "Example 061 - time-tagged commands",
        "Example 062 - commands with a release time",
        "Example 063 - load only command",
        "Example 064 - confirm command execution",
        "Example 065 - confirm critical command execution",
        "Example 066 - commands with arguments",
        "Example 067 - sending sequence",
        "Example 068 - sending a group of commands",
        "Example 069 - sending a group of commands with arguments",
        "Example 070 - sending a list of commands grouped",
        "Example 071 - sending a list of commands blocked",
        "Example 072 - sending with timeout",
        "Example 073 - additional information",
        "Example 074 - sending with delayed release",
        "Example 075 - sending and verifying",
        "Example 076 - sending, verifying and adjusting limits",
        "Example 077 - complex send",
        "Example 078 - wait relative time condition",
        "Example 079 - wait absolute time condition",
        "Example 080 - wait telemetry condition",
        "Example 081 - wait telemetry condition with maximum delay",
        "Example 082 - simple interval",
        "Example 083 - complex interval",
        "Example 084 - injecting parameters",
        "Example 085 - reading all limit definitions",
        "Example 086 - complex limit definitions for HARDSOFT limit",
        "Example 087 - complex limit definitions for STATUS limit",
        "Example 088 - reading applicable limit definitions",
        "Example 089 - reading limit definitions by identifier",
        "Example 090 - reading limit definitions from status parameters",
        "Example 091 - reading single data from limit definitions",
        "Example 092 - reading single data from limit definitions (2)",
        "Example 093 - reading single data from limit definitions (3)",
        "Example 094 - modifying limit definitions",
        "Example 095 - modifying limit definitions (2)",
        "Example 096 - modifying limit definitions (3)",
        "Example 097 - modifying limit definitions (4)",
        "Example 098 - modifying limit data for Status parameter",
        "Example 099 - modifying limit definitions (5)",
        "Example 100 - modifying limit definitions for SPIKE limit",
        "Example 101 - modifying limit definitions for STEP limit",
        "Example 102 - enabling and disabling alarms",
        "Example 103 - automatic limit adjustment for HARDSOFT parameter",
        "Example 104 - automatic limit adjustment for STATUS parameter",
        "Example 105 - loading limits from file",
        "Example 106 - restoring limits",
        "Example 107 - checking alarm status",
        "Example 108 - display messages",
        "Example 109 - sending notifications",
        "Example 110 - event messages",
        "Example 111 - change configuration value",
        "Example 112 - retrieve configuration value",
        "Example 113 - variable mappings with ground database",
        "Example 114 - types of prompt",
        "Example 115 - default prompt list",
        "Example 116 - custom list with index",
        "Example 117 - custom list with values",
        "Example 118 - default value for prompt",
        "Example 119 - opening displays",
        "Example 120 - opening a workspace",
        "Example 121 - specifying the host",
        "Example 122 - specifying the monitor",
        "Example 123 - specifying time span",
        "Example 124 - printing displays",
        "Example 125 - display format",
        "Example 126 - closing displays",
        "Example 127 - closing workspaces",
        "Example 128 - step definitions",
        "Example 129 - step and go-to",
        "Example 130 - displaying step information",
        "Example 131 - pausing, aborting and finishing",
        "Example 132 - setting user actions",
        "Example 133 - enabling/disabling user actions",
        "Example 134 - removing user actions",
        "Example 135 - spacecraft database",
        "Example 136 - spacecraft database keys",
        "Example 137 - checking spacecraft database keys",
        "Example 138 - loading a manoeuvre file",
        "Example 139 - ground database mappings",
        "Example 140 - using database mappings",
        "Example 141 - using database mappings (2)",
        "Example 142 - procedure database",
        "Example 143 - loading an user database file",
        "Example 144 - creating an user database file",
        "Example 145 - saving an user database file",
        "Example 146 - modifying a database value",
        "Example 147 - database data example",
        "Example 148 - database data example manipulation",
        "Example 149 - creating a data container",
        "Example 150 - declare a variable in a data container",
        "Example 151 - starting a sub-procedure",
        "Example 152 - procedure library example",
        "Example 153 - folder priorities",
        "Example 154 - starting procedure using priorities",
        "Example 155 - starting procedure overriding priorities",
        "Example 156 - starting a sub-procedure in non-blocking mode",
        "Example 157 - starting a sub-procedure in hidden mode",
        "Example 158 - starting a sub-procedure in manual mode",
        "Example 159 - starting a sub-procedure (complex)",
        "Example 160 - starting a sub-procedure with arguments",
        "Example 161 - accessing procedure arguments",
        "Example 162 - opening a file",
        "Example 163 - opening a file",
        "Example 164 - writing to a file",
        "Example 165 - reading file lines",
        "Example 166 - reading directory contents",
        "Example 167 - create a File instance",
        "Example 168 - deleting files and directories",
        "Example 169 - enabling or disabling the ranging system",
        "Example 170 - starting ranging activities",
        "Example 171 - starting dual ranging activities",
        "Example 172 - aborting ranging activities",
        "Example 173 - setting and getting baseband configurations",
        "Example 174 - getting BBE/Antennae information",
        "Example 175 - calibrate the ranging system",
        "Example 176 - status of the ranging system",
        "Example 177 - setting shared data values",
        "Example 178 - setting shared data values (2)",
        "Example 179 - setting shared data values (3)",
        "Example 180 - setting shared data values in a scope",
        "Example 181 - creating a scope",
        "Example 182 - test and set shared data values",
        "Example 183 - test and set shared data values (2)",
        "Example 184 - getting shared data values",
        "Example 185 - getting shared data values (2)",
        "Example 186 - getting shared data values (3)",
        "Example 187 - getting shared data information",
        "Example 188 - clearing shared data values",
        "Example 189 - clearing shared data scopes",
        "Example 190 - clearing shared data scopes",
        "Example 191 - generate memory reports",
        "Example 192 - compare memory images",
        "Example 193 - compare memory images on limited data ranges",
        "Example 194 - extract memory values",
        "Example 195 - extract TM/TC database values",
    ],
    list_mode="INDEX",
    default=0,
    target=selected_index,
)
example_number = selected_index + 1
ReferenceExample(example_number, target=result)
Log(result)
