# @procedure language_reference_244
# @display-name SPELL 2.4.4 language checks
# @description Select an adaptation, direct source or rejection check; gaps remain explicit
# @language-profile spell-lrm244-conformance/0.19
"""SPELL 2.4.4 coverage: 763 artifacts. Full language support remains incomplete."""

selected_index: int = 0
example_number: int = 1
result: str = "not run"

Prompt(
    "Select a SPELL 2.4.4 reference example",
    type="LIST",
    choices=[
        "Example 001 - indentation",
        "Example 002 - splitting character strings",
        "Example 003 - splitting with comma",
        "Example 004 - splitting code with backslash",
        "Example 005 - single line comments in python",
        "Example 006 - multi-line comments in python",
        "Example 007 - variable types in Python",
        "Example 008 - lists and dictionaries",
        "Example 009 - arithmetic expressions",
        "Example 010 - boolean expressions",
        "Example 011 - string expressions",
        "Example 012 - substrings",
        "Example 013 - conditional statements",
        "Example 014 - for loop statements",
        "Example 015 - while loop statements",
        "Example 016 - user defined function example",
        "Example 017 - arguments by reference",
        "Example 018 - module (procedure) import",
        "Example 019 - SPELL function with keyword parameters",
        "Example 020 - changing defaults for a function in a procedure",
        "Example 021 - failure action configuration",
        "Example 022 - automatic failure processing",
        "Example 023 - reacting on function result",
        "Example 024 - special error handling",
        "Example 025 - silent execution",
        "Example 026 - using NOW in a loop",
        "Example 027 - using NOW in a loop (2)",
        "Example 028 - modifying the output time format",
        "Example 029 - time management",
        "Example 030 - obtain engineering TM values",
        "Example 031 - waiting for updates",
        "Example 032 - waiting for updates with timeout",
        "Example 033 - acquisition of raw value",
        "Example 034 - acquisition extended information",
        "Example 035 - verify a single TM value",
        "Example 036 - verify a single TM value in raw format",
        "Example 037 - verify using next update and timeout",
        "Example 038 - verify with tolerance",
        "Example 039 - using Verify in a test statement",
        "Example 040 - getting failure information",
        "Example 041 - getting failure information (output)",
        "Example 042 - do nothing on False",
        "Example 043 - do not prompt the user and take the SKIP action",
        "Example 044 - repeat verification if it fails, 2 times",
        "Example 045 - delay the verification",
        "Example 046 - ignoring string value case",
        "Example 047 - multiple verifications",
        "Example 048 - multiple verifications and configurations",
        "Example 049 - multiple verifications and configurations (2)",
        "Example 050 - verifications with multiple values",
        "Example 051 - comparing telemetry parameters",
        "Example 052 - comparing telemetry parameters (wrong code)",
        "Example 053 - comparing telemetry parameters with items",
        "Example 054 - comparing telemetry parameters with lists of items",
        "Example 055 - building a simple command",
        "Example 056 - building a simple command",
        "Example 057 - building a simple command",
        "Example 058 - command arguments",
        "Example 059 - building a command with arguments",
        "Example 060 - sending a simple command",
        "Example 061 - time-tagged commands",
        "Example 062 - commands with a release time",
        "Example 063 - load only command",
        "Example 064 - confirm command execution",
        "Example 065 - confirm critical command execution",
        "Example 066 - commands with arguments",
        "Example 067 - sending sequence",
        "Example 068 - sending a group of commands",
        "Example 069 - sending a group of commands with arguments",
        "Example 070 - sending a list of commands grouped",
        "Example 071 - sending a list of commands blocked",
        "Example 072 - sending with timeout",
        "Example 073 - additional information",
        "Example 074 - sending with delayed release",
        "Example 075 - sending and verifying",
        "Example 076 - sending, verifying and adjusting limits",
        "Example 077 - complex send",
        "Example 078 - wait relative time condition",
        "Example 079 - wait absolute time condition",
        "Example 080 - wait telemetry condition",
        "Example 081 - wait telemetry condition with maximum delay",
        "Example 082 - simple interval",
        "Example 083 - complex interval",
        "Example 084 - injecting parameters",
        "Example 085 - reading all limit definitions",
        "Example 086 - complex limit definitions for HARDSOFT limit",
        "Example 087 - complex limit definitions for STATUS limit",
        "Example 088 - reading applicable limit definitions",
        "Example 089 - reading limit definitions by identifier",
        "Example 090 - reading limit definitions from status parameters",
        "Example 091 - reading single data from limit definitions",
        "Example 092 - reading single data from limit definitions (2)",
        "Example 093 - reading single data from limit definitions (3)",
        "Example 094 - modifying limit definitions",
        "Example 095 - modifying limit definitions (2)",
        "Example 096 - modifying limit definitions (3)",
        "Example 097 - modifying limit definitions (4)",
        "Example 098 - modifying limit data for Status parameter",
        "Example 099 - modifying limit definitions (5)",
        "Example 100 - modifying limit definitions for SPIKE limit",
        "Example 101 - modifying limit definitions for STEP limit",
        "Example 102 - enabling and disabling alarms",
        "Example 103 - automatic limit adjustment for HARDSOFT parameter",
        "Example 104 - automatic limit adjustment for STATUS parameter",
        "Example 105 - loading limits from file",
        "Example 106 - restoring limits",
        "Example 107 - checking alarm status",
        "Example 108 - display messages",
        "Example 109 - sending notifications",
        "Example 110 - event messages",
        "Example 111 - change configuration value",
        "Example 112 - retrieve configuration value",
        "Example 113 - variable mappings with ground database",
        "Example 114 - types of prompt",
        "Example 115 - default prompt list",
        "Example 116 - custom list with index",
        "Example 117 - custom list with values",
        "Example 118 - default value for prompt",
        "Example 119 - opening displays",
        "Example 120 - opening a workspace",
        "Example 121 - specifying the host",
        "Example 122 - specifying the monitor",
        "Example 123 - specifying time span",
        "Example 124 - printing displays",
        "Example 125 - display format",
        "Example 126 - closing displays",
        "Example 127 - closing workspaces",
        "Example 128 - step definitions",
        "Example 129 - step and go-to",
        "Example 130 - displaying step information",
        "Example 131 - pausing, aborting and finishing",
        "Example 132 - setting user actions",
        "Example 133 - enabling/disabling user actions",
        "Example 134 - removing user actions",
        "Example 135 - spacecraft database",
        "Example 136 - spacecraft database keys",
        "Example 137 - checking spacecraft database keys",
        "Example 138 - loading a manoeuvre file",
        "Example 139 - ground database mappings",
        "Example 140 - using database mappings",
        "Example 141 - using database mappings (2)",
        "Example 142 - procedure database",
        "Example 143 - loading an user database file",
        "Example 144 - creating an user database file",
        "Example 145 - saving an user database file",
        "Example 146 - modifying a database value",
        "Example 147 - database data example",
        "Example 148 - database data example manipulation",
        "Example 149 - creating a data container",
        "Example 150 - declare a variable in a data container",
        "Example 151 - starting a sub-procedure",
        "Example 152 - procedure library example",
        "Example 153 - folder priorities",
        "Example 154 - starting procedure using priorities",
        "Example 155 - starting procedure overriding priorities",
        "Example 156 - starting a sub-procedure in non-blocking mode",
        "Example 157 - starting a sub-procedure in hidden mode",
        "Example 158 - starting a sub-procedure in manual mode",
        "Example 159 - starting a sub-procedure (complex)",
        "Example 160 - starting a sub-procedure with arguments",
        "Example 161 - accessing procedure arguments",
        "Example 162 - opening a file",
        "Example 163 - opening a file",
        "Example 164 - writing to a file",
        "Example 165 - reading file lines",
        "Example 166 - reading directory contents",
        "Example 167 - create a File instance",
        "Example 168 - deleting files and directories",
        "Example 169 - enabling or disabling the ranging system",
        "Example 170 - starting ranging activities",
        "Example 171 - starting dual ranging activities",
        "Example 172 - aborting ranging activities",
        "Example 173 - setting and getting baseband configurations",
        "Example 174 - getting BBE/Antennae information",
        "Example 175 - calibrate the ranging system",
        "Example 176 - status of the ranging system",
        "Example 177 - setting shared data values",
        "Example 178 - setting shared data values (2)",
        "Example 179 - setting shared data values (3)",
        "Example 180 - setting shared data values in a scope",
        "Example 181 - creating a scope",
        "Example 182 - test and set shared data values",
        "Example 183 - test and set shared data values (2)",
        "Example 184 - getting shared data values",
        "Example 185 - getting shared data values (2)",
        "Example 186 - getting shared data values (3)",
        "Example 187 - getting shared data information",
        "Example 188 - clearing shared data values",
        "Example 189 - clearing shared data scopes",
        "Example 190 - clearing shared data scopes",
        "Example 191 - generate memory reports",
        "Example 192 - compare memory images",
        "Example 193 - compare memory images on limited data ranges",
        "Example 194 - extract memory values",
        "Example 195 - extract TM/TC database values",
        "Direct - scalar-inference",
        "Direct - arithmetic",
        "Direct - boolean-and-comparison",
        "Direct - short-circuit",
        "Direct - comments-and-continuation",
        "Direct - case-sensitive-names",
        "Direct - conditional",
        "Direct - bounded-range",
        "Direct - reverse-range",
        "Direct - local-function",
        "Direct - display-default",
        "Direct - display-positional",
        "Direct - display-keyword",
        "Direct - integer-literals",
        "Direct - runtime-division-error",
        "Direct - recovery-fresh-run",
        "Gap check - reject-type-change",
        "Gap check - reject-branch-declaration",
        "Gap check - reject-import",
        "Gap check - reject-while",
        "Gap check - reject-list",
        "Gap check - reject-dictionary",
        "Gap check - reject-function-arguments",
        "Gap check - reject-exception-syntax",
        "Gap check - reject-silent-display",
        "Gap check - reject-display-duplicate",
        "Gap check - reject-display-invalid-severity",
        "Gap check - reject-display-missing-text",
        "Gap check - reject-display-type",
        "Gap check - reject-severity-shadow",
        "Gap check - reject-attribute",
        "Gap check - reject-source-evaluation",
        "Direct - v17-core-arithmetic-precedence",
        "Direct - v17-core-signed-modulus",
        "Direct - v17-core-mixed-numeric",
        "Direct - v17-core-chained-short-circuit",
        "Direct - v17-core-chained-all-true",
        "Direct - v17-core-boolean-short-circuit",
        "Direct - v17-core-boolean-evaluated-error",
        "Direct - v17-core-if-first-captured",
        "Direct - v17-core-if-elif",
        "Direct - v17-core-if-else",
        "Direct - v17-core-if-no-else",
        "Direct - v17-core-nested-dead-condition",
        "Direct - v17-core-empty-range",
        "Direct - v17-core-equal-range",
        "Direct - v17-core-wrong-direction-ranges",
        "Direct - v17-core-empty-retains-prior-index",
        "Direct - v17-core-singleton-range",
        "Direct - v17-core-negative-step-range",
        "Direct - v17-core-maximum-range",
        "Direct - v17-core-nested-empty-range",
        "Direct - v17-core-bitwise-signed",
        "Direct - v17-core-bitwise-bound",
        "Direct - v17-core-power-sign-precedence",
        "Direct - v17-core-power-zero-one",
        "Direct - v17-core-power-result-bound",
        "Direct - v17-core-power-result-overflow",
        "Direct - v17-core-power-variable-negative",
        "Direct - v17-core-power-variable-overflow",
        "Direct - v17-core-float-result-overflow",
        "Gap check - v17-core-reject-zero-step",
        "Gap check - v17-core-reject-range-overflow",
        "Gap check - v17-core-reject-dynamic-range",
        "Gap check - v17-core-reject-dead-body-import",
        "Gap check - v17-core-reject-dead-body-call",
        "Gap check - v17-core-reject-empty-index-read",
        "Gap check - v17-core-reject-integer-literal-overflow",
        "Gap check - v17-core-reject-nonfinite-literal",
        "Gap check - v17-core-reject-power-negative-literal",
        "Gap check - v17-core-reject-power-exponent-bound",
        "Gap check - v17-core-reject-power-float",
        "Gap check - v17-core-reject-bitwise-bool",
        "Gap check - v17-core-reject-numeric-condition",
        "Direct - v17-prompt-ok",
        "Direct - v17-prompt-cancel",
        "Direct - v17-prompt-ok-cancel",
        "Direct - v17-prompt-yes",
        "Direct - v17-prompt-no",
        "Direct - v17-prompt-yes-no",
        "Direct - v17-prompt-default-type",
        "Direct - v17-prompt-alpha",
        "Direct - v17-prompt-number",
        "Direct - v17-prompt-date",
        "Direct - v17-prompt-list-key",
        "Direct - v17-prompt-list-numeric-key",
        "Direct - v17-prompt-list-index",
        "Direct - v17-prompt-list-value",
        "Direct - v17-prompt-default-deadline-declaration",
        "Direct - v17-prompt-warning-only-declaration",
        "Direct - v17-prompt-zero-timeout",
        "Direct - v17-prompt-default-without-timeout",
        "Direct - v17-prompt-cancel-no-result",
        "Direct - v17-display-empty",
        "Direct - v17-display-dynamic-empty",
        "Direct - v17-display-whitespace",
        "Direct - v18-native-yes-built-command",
        "Direct - v18-native-no-no-dispatch",
        "Direct - v18-native-cancel-no-dispatch",
        "Direct - v18-numeric-guard-sends",
        "Direct - v18-numeric-guard-skips",
        "Direct - v18-native-plus-command-confirmation",
        "Direct - v18-command-confirmation-denied",
        "Direct - v18-default-no-policy-declaration",
        "Direct - v18-direct-command-empty-display",
        "Direct - v18-built-literal-arguments",
        "Direct - v18-load-only-is-not-execution",
        "Direct - v18-sequential-group",
        "Direct - v18-inherited-direct-send",
        "Direct - v18-sequence-expansion",
        "Direct - v18-block-group-transport",
        "Direct - v18-group-shared-transport",
        "Direct - v18-critical-confirmation",
        "Direct - v18-absolute-command-time",
        "Direct - v18-relative-release-intent",
        "Direct - v18-bounded-delay-and-timeout",
        "Direct - v18-literal-radix-format",
        "Direct - v18-additional-driver-info",
        "Direct - v18-verification-success",
        "Direct - v18-per-command-override",
        "Direct - v18-successful-failure-policy",
        "Direct - v18-transport-rejection-continue",
        "Direct - v18-transport-rejection-prompt-user",
        "Direct - v18-verification-failure-stops",
        "Gap check - v18-reject-native-command-selector",
        "Gap check - v18-reject-native-command-argument",
        "Gap check - v18-reject-mixed-data-service",
        "Gap check - v18-reject-nested-language-service",
        "Direct - v19-observation-prompt-confirm-command",
        "Direct - v19-observation-native-no",
        "Direct - v19-observation-native-abort",
        "Direct - v19-observation-confirmation-no",
        "Direct - v19-observation-false-decision",
        "Direct - v19-read-rejects-missing",
        "Direct - v19-read-rejects-stale",
        "Direct - v19-read-rejects-invalid",
        "Direct - v19-read-rejects-bad-quality",
        "Direct - v19-read-rejects-gap",
        "Direct - v19-read-rejects-policy",
        "Direct - v19-clock-indeterminate-no-command",
        "Direct - v19-verify-overwrites-prior-true",
        "Direct - v19-condition-wait-command",
        "Direct - v19-condition-wait-timeout-no-command",
        "Direct - v19-read-controls-bounded-loop",
        "Direct - v19-read-native-built-command",
        "Gap check - v19-reject-observation-dynamic-command",
        "Gap check - v19-reject-observation-dynamic-argument",
        "Gap check - v19-reject-observation-data-mixture",
        "Run all language checks and adaptations; report gaps",
    ],
    list_mode="INDEX",
    default=0,
    target=selected_index,
)
example_number = selected_index + 1
LanguageCheck(selected_index, profile="0.19", target=result)
Log(result)
