# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from spell.driver.dss.v1 import dss_pb2 as spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in spell/driver/dss/v1/dss_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DssServiceStub:
    """Additive local-only DSS boundary. Authentication remains mutual TLS with the
    existing gateway identity. No endpoint, credential, or source code is accepted.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/spell.driver.dss.v1.DssService/Health',
                request_serializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.HealthRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ClockEvidence = channel.unary_unary(
                '/spell.driver.dss.v1.DssService/ClockEvidence',
                request_serializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.HealthRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.ClockEvidenceResponse.FromString,
                _registered_method=True)
        self.CommandStage = channel.unary_unary(
                '/spell.driver.dss.v1.DssService/CommandStage',
                request_serializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.CommandStageRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.CommandStageResponse.FromString,
                _registered_method=True)
        self.PacketEvidence = channel.unary_unary(
                '/spell.driver.dss.v1.DssService/PacketEvidence',
                request_serializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.PacketEvidenceRequest.SerializeToString,
                response_deserializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.PacketEvidenceResponse.FromString,
                _registered_method=True)


class DssServiceServicer:
    """Additive local-only DSS boundary. Authentication remains mutual TLS with the
    existing gateway identity. No endpoint, credential, or source code is accepted.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClockEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommandStage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PacketEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DssServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.HealthRequest.FromString,
                    response_serializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.HealthResponse.SerializeToString,
            ),
            'ClockEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.ClockEvidence,
                    request_deserializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.HealthRequest.FromString,
                    response_serializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.ClockEvidenceResponse.SerializeToString,
            ),
            'CommandStage': grpc.unary_unary_rpc_method_handler(
                    servicer.CommandStage,
                    request_deserializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.CommandStageRequest.FromString,
                    response_serializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.CommandStageResponse.SerializeToString,
            ),
            'PacketEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.PacketEvidence,
                    request_deserializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.PacketEvidenceRequest.FromString,
                    response_serializer=spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.PacketEvidenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spell.driver.dss.v1.DssService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spell.driver.dss.v1.DssService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DssService:
    """Additive local-only DSS boundary. Authentication remains mutual TLS with the
    existing gateway identity. No endpoint, credential, or source code is accepted.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.dss.v1.DssService/Health',
            spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.HealthRequest.SerializeToString,
            spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClockEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.dss.v1.DssService/ClockEvidence',
            spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.HealthRequest.SerializeToString,
            spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.ClockEvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommandStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.dss.v1.DssService/CommandStage',
            spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.CommandStageRequest.SerializeToString,
            spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.CommandStageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PacketEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spell.driver.dss.v1.DssService/PacketEvidence',
            spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.PacketEvidenceRequest.SerializeToString,
            spell_dot_driver_dot_dss_dot_v1_dot_dss__pb2.PacketEvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
